### PR TITLE
Hardknott

### PR DESCRIPTION
**Pull request by kueken**
not ready yet

### CODE REVIEW

**Review by andrea-adami — COMMENTED** [review]
Hi kueken,
FWIW I am  using 1.50 @ 9b2d96b because it backports the new append syntax.

**Comment by kueken** [comment]
You mean branch 'bitbake'?
I have now followed the 'hardknott' structure.
This then fits in with the rest.
But if something else works better or a different path is given, then that's okay too.

Regards

**Review by andrea-adami — COMMENTED** [review]
kueken:

thanks so much for your commits.

About the changes like 
-CONFFILES_${PN} = "${sysconfdir}/inadyn.conf"
-CONFFILES_${PN} = "/etc/inadyn.conf"

 I  respect your opinion but as for OpenEmbedded this is just bad behavior.
All is defined in bitbake.conf, ready for multilib and eventual separate /usr (no usrmerge distro feat).

Just my 2 cents.

**Comment by kueken** [comment]
no problem.
There are still a few problems to be resolved.

Regards

**Comment by WanWizard** [comment]
> All is defined in bitbake.conf, ready for multilib and eventual separate /usr (no usrmerge distro feat).

Agreed, please don't hardcode paths.

**Comment by andrea-adami** [comment]
kueken:
let me try with samba/libtalloc this week-end.
I'll build first in oe-core for qemu, built with python2.

About the OE-A samba, I don't trust it that much.
It did not build correctly on my test, see https://github.com/oe-alliance/build-enviroment/issues/46

Cheers
A.A.

**Comment by kueken** [comment]
reset and remove hardcode path

**Pull request merged**
