### PR TITLE
diet for python

### PR DESCRIPTION
**Pull request by ims21**
- i do not know, why is still attached merged pr too (autosf)

### CODE REVIEW

**Comment by WanWizard** [comment]
I'll see if I can pry that one out later today.

**Comment by ims21** [comment]
It is not important ...
How can I stop adding old (merged) PR to next created PR ?  (Autofs was merged yet)

**Comment by WanWizard** [comment]
Probably because your local develop wasn't in sync, so git still saw the change?

**Comment by eriksl** [comment]
I think you need to branch off a new branch for each PR.

**Comment by eriksl** [comment]
Cherry-picked the remaining commit.

**Pull request closed without merging**
