### PR TITLE
dos2unix files

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by atvcaptain** [comment]
patch files dont change it its a bad idea

**Comment by WanWizard** [comment]
I think that happened in a previous one too?

**Comment by persianpros** [comment]
No, I think rebuilding of packages because of patch changes is what he means.

**Comment by WanWizard** [comment]
I can live with that. 

As long as the patches apply correctly, I assume CRLF line ends were there because they were in the source, and therefore ended up in the diff. Which means it would have been correct for the CRLF to be there.

**Pull request closed without merging**
