### PR TITLE
openpli-common.conf: use default FULL_OPTIMIZATION -O2 OE-core

### PR DESCRIPTION
**Pull request by Hains**
For better performance.
This increasing the image size a bit(2.5MB for dm8000).

Small cosmetic change in comment.

Thanks to Athoik.

### CODE REVIEW

**Comment by athoik** [comment]
What about performance? I am sure there will be small gains everywhere (faster python, e2, etc).

**Comment by eriksl** [comment]
I am worried about first gen receivers, like xtrend 9x00 and vuduo, that may not have enough flash.

**Comment by Hains** [comment]
I created an image for et9x00 with the latest development with -O2 as default (note: I had to update e2fsprogs to 1.43.8 and qemu to 2.11.1) and extracted the zip file.

The created et9x00 folder has a size of 95 MB.

About performance:
I did not notice performance improvement with dm8000.
O2 will probably be faster, but we're not talking about seconds but about milliseconds.

With -O3 as default I notice a little less delay in the use of gstreamer.
Somewhat faster startup of streams / files.
And for example, a restart of enigma2:
With -Os and -O2 as default: +/- 42 seconds.
With -O3 as default: +/- 35 seconds.

So, -O3 has a speed improvement of about 16%.
But from O2 to O3 as default , increases the image size by 3MB.

**Comment by eriksl** [comment]
How much increase in image size from Os to O2?

**Comment by RobvanderDoes** [comment]
> I am worried about first gen receivers, like xtrend 9x00 and vuduo, that may not have enough flash.

After confirming that this is indeed an issue: why not stop building those images? You can't support ancient boxes forever; there comes an end to it, otherwise innovation can never take place.

**Comment by Hains** [comment]
```
How much increase in image size from Os to O2?
```

With -Os: (without this PR)   91.9MB   (zipfile 70.9MB).
With -O2: (with this PR)        95.0MB   (zipfile 73.3MB)

So 95-91.9 = 3.1MB.

**Comment by eriksl** [comment]
That might make the difference voor older generations receivers. We may consider not apply it for them.

**Comment by littlesat** [comment]
+1,
Unless find a way to implement it only for the boxes with bigger flash...

**Comment by eriksl** [comment]
There is a way, but I don't like it:
- it requires per-machine overrides, these belong in the BSP
- it may result in bugs showing in some machines and not in others, difficult to debug

**Comment by athoik** [comment]
Maybe switch to O2 as default and change E2 to O3?

**Pull request closed without merging**
