### PR TITLE
Exteplayer3

### PR DESCRIPTION
**Pull request by kueken**

### CODE REVIEW

**Comment by kueken** [comment]
Sorry for bad Information in title
Simply pressed the wrong button.
Exteplyer3 revision updtate
gst update last stand
ffmpeg update 4.3.1
add x265 
Adaptation of the preffered version

A lot can certainly be adjusted, but that's how it works and builds it flawlessly.
greetings

**Comment by WanWizard** [comment]
Thanks :+1:  

Running a test build now.

**Comment by WanWizard** [comment]
Hmmm, one of those days....
```
Cloning into bare repository '/data/openpli/sources/git2/gitlab.freedesktop.org.gstreamer.gst-plugins-bad'...

error: RPC failed; result=22, HTTP code = 404
fatal: The remote end hung up unexpectedly

```

**Comment by kueken** [comment]
Server problems?

**Comment by WanWizard** [comment]
at the freedesktop.org end, yes, looks like it...

Manually:
```
$ git clone git://gitlab.freedesktop.org/gstreamer/gst-plugins-bad;protocol=https;branch=master;name=gst_plugins_bad
Cloning into 'gst-plugins-bad'...
fatal: unable to connect to gitlab.freedesktop.org:
gitlab.freedesktop.org[0: 35.227.58.183]: errno=Connection timed out
```

**Comment by kueken** [comment]
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad
works here now without problems

**Comment by WanWizard** [comment]
The problem isn't with the gitlab web interface, it's with the git (ssh) interface.

**Comment by kueken** [comment]
clone via https works fine

**Comment by WanWizard** [comment]
I know, but that is not what bitbake is using...
````
ERROR: gstreamer1.0-plugins-base-1.17.90+gitAUTOINC+94dcf915e8-r0 do_fetch: Fetcher failure for URL: 'git://gitlab.freedesktop.org/gstreamer/gst-plugins-base;protocol=https;branch=master;name=gst_plugins_base'. Unable to fetch URL from any source.
````
Tomorrow is another day...

**Comment by WanWizard** [comment]
Found the culprit. The SRC_URI's need to have a ".git" extension, otherwise git tries to clone a gitlab webpage.

**Comment by kueken** [comment]
I do not understand the problems, had created a completely identical branch and ran some test builds.
sf8008
Formuler f1
xtrend et9x00
as a feed
and everything was fine
https://github.com/kueken/openpli-oe-core

can it be that there are still some old things on the server?

**Comment by WanWizard** [comment]
For gitlab,
````
git://gitlab.freedesktop.org/gstreamer/gst-plugins-base;protocol=https
````
and
````
git://gitlab.freedesktop.org/gstreamer/gst-plugins-base.git;protocol=https
````
are two different URL's.  Check the "clone" button  on https://gitlab.freedesktop.org/gstreamer/gst-plugins-base.

**Comment by WanWizard** [comment]
With this it works fine on our buildservers, currently busy spliitting the PR into it's components and cleaning them up for manual merge, will commit them in a minute...

**Comment by kueken** [comment]
Yes, the big commit was not wanted, sorry ...
Individual commits were planned, but unfortunately the system was faster and so I left it.
But I can do it again individually if I want.
greetings

**Comment by WanWizard** [comment]
No worries, need to clean up some whitespace issues as well, and move SRCREV's back into reporefs.conf.

**Comment by WanWizard** [comment]
Pushed.

**Comment by WanWizard** [comment]
First complete build run has finished, all MACHINE's build, except the dm8000.
````
2020-08-28 19:23:24 Summary: 1 task failed:
2020-08-28 19:23:24   /openpli/oe/develop/meta-openpli/recipes-multimedia/gstreamer/gstreamer1.0-plugin-dvbmediasink.bb:do_patch
2020-08-28 19:23:24 Summary: There was 1 ERROR message shown, returning a non-zero exit code.
````
with
````
NOTE: Applying patch 'dmm.patch' (../meta-dream/recipes-multimedia/gstreamer/gstreamer1.0-plugin-dvbmediasink/dmm.patch)
ERROR: Command Error: 'quilt --quiltrc /openpli/oe/develop/build/tmp/work/dm8000-oe-linux/gstreamer1.0-plugin-dvbmediasink/1.0+gitAUTOINC+6e61722bcc-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch dmm.patch
patching file gstdvbaudiosink.c
Hunk #1 FAILED at 1076.
Hunk #2 FAILED at 1102.
2 out of 2 hunks FAILED -- rejects in file gstdvbaudiosink.c
patching file gstdvbaudiosink.h
Hunk #1 succeeded at 97 with fuzz 2 (offset 19 lines).
patching file gstdvbvideosink.c
Hunk #1 FAILED at 1656.
Hunk #2 FAILED at 1683.
2 out of 2 hunks FAILED -- rejects in file gstdvbvideosink.c
patching file gstdvbvideosink.h
Hunk #1 succeeded at 131 (offset 60 lines).
Patch dmm.patch does not apply (enforce with -f)
````
Is this patch still needed, now that we've switched mediasink?

**Comment by kueken** [comment]
i didn't notice the patch.
Comes from the dream area.
Presumably it is no longer needed.
wait for @athoik

**Comment by WanWizard** [comment]
Ok, thanks. This is above my skill level... :grin:

**Comment by kueken** [comment]
@Hains 
Can certainly say more about Dream.
In my opinion, the patches are no longer necessary and should be deleted.
I actually didn't pay attention to them in the dream area, otherwise I would have deleted them too.
greetings

**Comment by athoik** [comment]
You need those patches for dreambox.

**Comment by kueken** [comment]
Have you seen the change to the new dvbmediasink?
The patches are already there via 'if dreambox'
contain
for example here
https://github.com/christophecvr/gstreamer1.0-plugin-multibox-dvbmediasink/blob/openatv-dev/gstdvbaudiosink.c#L1406-L1410

**Comment by athoik** [comment]
Why we abandoned OpenPLi dvbmediasink?

**Comment by kueken** [comment]
No not given up ...
It was just an update to the current medihandling gst / ffmpeg ...
You could of course also change this to pli dvbmediasink and convert it accordingly.

**Comment by athoik** [comment]
I prefer that you will change it back to OpenPLi version.

Thanks.

**Comment by kueken** [comment]
https://github.com/OpenPLi/openpli-oe-core/pull/857

**Pull request closed without merging**
