### PR TITLE
zgemma: update bsp

### PR DESCRIPTION
**Pull request by Taapat**
h3: move plugin vfdcontrol from image to feed

Please use together with this: https://github.com/OpenPLi/enigma2/pull/607

### CODE REVIEW

**Comment by zgemma-star** [comment]
please add in meta-openpli/recipes-openpli/enigma2/enigma2.bb 
EXTRA_OECONF = "\
line: ${@base_contains("MACHINE_FEATURES", "7segment", "--with-7segment" , "", d)} \

**Comment by Taapat** [comment]
For compatibility with other bsp would be better to use 7seg which is currently used to install a enigma2-plugin-systemplugins-vfdcontrol.
But I did not want to do this at the moment until I satisfied that my skin_text.xml working on all of these receivers.
But there is no problem in this moment add 7segment, if you want to use it, and later also add 7seg.

**Comment by zgemma-star** [comment]
Actually we want to install as few as possible plugins from BSP and only define machine features.

I prefer to use as MACHINE_FEATURES ="7segment" but if you prefer we can change it in 7seg but this is now used by OPENPLI_FEATURES. With your great solution for the 7segment display problem we will remove the VFD plugin entire from BSP.

I hope you can specify the 7segment or 7seg into enigma2.bb so that the new 7segment display skin will been add in the new builds.

**Comment by Taapat** [comment]
Ok I added 7segment on this moment.

**Pull request merged**
