### PR TITLE
tryfix build errors Kodi (file-rdeps)

### PR DESCRIPTION
**Pull request by kueken**

### CODE REVIEW

**Comment by WanWizard** [comment]
That's it, I think. Have you tested it?

**Comment by kueken** [comment]
Test build is fine.
I can't say to what extent Kodi works.
I lack the hardware ;-)

Another build error from
https://github.com/OpenPLi/tuxbox-xml/commits/master
last commit today.
Commit before seems ok.

**Comment by WanWizard** [comment]
No worries, it didn't work before either :grin: (hence the attempts to fix it).

**Comment by WanWizard** [comment]
> Another build error from
> https://github.com/OpenPLi/tuxbox-xml/commits/master
> last commit today.
> Commit before seems ok.

Can we discuss this elsewhere? And what error, I don't see any issue in the output?

**Pull request merged**
