### PR TITLE
add glibc patches fix trouble with Kodi

### PR DESCRIPTION
**Pull request by kueken**
thx OE-Alliance

### CODE REVIEW

**Comment by WanWizard** [comment]
Another full rebuild...

**Comment by kueken** [comment]
Not quite, but 'only' for arm (hisi / BCM) but not for mips.
But it's about patching, I would also transfer it to 8.1.
But do not know how it is wanted.

**Comment by WanWizard** [comment]
Lets see how it builds in develop first (and if it actually works :grin:).

**Comment by kueken** [comment]
functions
Otherwise I wouldn't have sent it as PR ;-)
ask with User doglover;-)

**Comment by kueken** [comment]
Another problem is missing alsa support in many bsp

**Pull request merged**
