### PR TITLE
Sumo eudev revert

### PR DESCRIPTION
**Pull request by zgemma-star**
eudev seems not ready yet and often is clears all the data of the usb storage devices.
I would suggest to use mdev for the time being.

it would been nice if sumo branch will turn to develop branch and that we can fix the final built issues.

### CODE REVIEW

**Comment by WanWizard** [comment]
I think this is being looked at. @eriksl @betacentauri ?

**Comment by betacentauri** [comment]
We are aware of this. First analysis was done. Populate-volatile.sh deletes the data on first boot after flashing when it creates /run/media link.

**Comment by zgemma-star** [comment]
So why not make a subbranch for eudev and systemd development till it become functional. 
Mdev always did the job well and in sumo it still does.
It seems to finalize sumo branch with mdev is not a huge job anymore as most is done already.

**Comment by littlesat** [comment]
As far I understand we also wanted to change to udef with sumo+

**Pull request closed without merging**
