### PR TITLE
restructure steamlink build and update last release

### PR DESCRIPTION
**Pull request by kueken**
add pycountry
delete is639/iso3166

### CODE REVIEW

**Comment by WanWizard** [comment]
You're sure they aren't used elsewhere?

**Comment by kueken** [comment]
Pycountry should be the solution for this.
All iso are included there.
But I check again whether it is still depend somewhere

**Comment by kueken** [comment]
Ok
I can't find any other addiction.
From my point of view, it is no longer needed.
If a plugin specifies this as a Depend, then the pycountry is also possible.

**Comment by WanWizard** [comment]
I asked because the commit message in release-7.3 was
> added missing python packages isodate, iso3166, iso639 and websocket 

which suggests something (a plugin perhaps) needs it.

**Comment by kueken** [comment]
Streamlink needs this ;-)
I have now rebuilt it and added pycountry for it.
At first it was just too big, but with the trick of removing the 'po' files, pycountry is not bigger.

**Comment by kueken** [comment]
;-)

**Pull request closed without merging**
