### PR TITLE
p8platform: remove, fix build of kodi pvr addons

### PR DESCRIPTION
**Pull request by andrea-adami**
after the update our recipe broke the compilation of some plugins.
While there is a lot to clean there, for now fix the build.

The recipe in meta-oe has a patch for CMake which seems fixing.

Signed-off-by: Andrea Adami <andrea.adami@gmail.com>

### CODE REVIEW

**Comment by WanWizard** [comment]
Can't merge this, it has a conflict. Your local clone not rebased?

**Comment by andrea-adami** [comment]
please keep on hold a bit more

**Comment by WanWizard** [comment]
Ok :grimacing:

**Comment by andrea-adami** [comment]
superseded

**Pull request closed without merging**
