### PR TITLE
Rocko build updates

### PR DESCRIPTION
**Pull request by Axas-UHD**

### CODE REVIEW

**Comment by chrsandb** [comment]
Alternative new SRC_URIs:

python-wifi: http://src.fedoraproject.org/repo/pkgs/${PN}/${P}.tar.bz2/8fe7fd0a4edce1f9bedaff4acb7fd500/${P}.tar.bz2
mutagen: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mutagen/mutagen-${PV}.tar.gz

**Comment by persianpros** [comment]
Who's using rocko?

**Comment by eriksl** [comment]
We, in the near future.

**Comment by MastaG** [comment]
@eriksl Could you please merge my commit for FFMPeg 3.4.2 into rocko? https://github.com/OpenPLi/openpli-oe-core/commit/cae43771c2fe10db93d973fe784b29e4f7aa07c8

@zgemma-star Could you please rebase your changes on top of my commit?
You can enable/disable any configure options you like (encoders, decoders etc..) but please leave the patches as they make exteplayer3 happy for samsamsam's IPTV Player :)

EDIT:
Or just enable everything instead as there's no supported receivers with small flash anymore.

**Comment by zgemma-star** [comment]
@MastaG, yes we should wait for the merge with the daisy/develop branch. I already revert the ffmpeg update to avoid more conflicts.
After the merge is done I will check again if we miss any codec for our platform.

**Comment by eriksl** [comment]
The planning is like this:
* finish release 6.2
* rebase rocko to current develop (which is pyro)
* pick all the pieces and get it working again (like always)
* merge all the stuff from a.o. zgemma for rocko
* only when everything works, create a new rocko branch, completely cleaned up and merge it into develop

So be careful with creating PR's against the rocko branch, it's volatile.

**Pull request closed without merging**
