### PR TITLE
update files streamlink

### PR DESCRIPTION
**Pull request by kueken**

### CODE REVIEW

**Comment by kueken** [comment]
please also take over in 8.1 and then my recommendation there Streamlink pin to the release version

**Comment by WanWizard** [comment]
so pin in develop too?

**Comment by kueken** [comment]
Better to Pin "Billy's" release.
The updates or takeovers of Billy from the original streamlink(python3) branch in the meantime lead to errors again and again.
It is better to follow the release and always update the additional files.

**Comment by WanWizard** [comment]
I have no idea what that means... :grin:

**Comment by kueken** [comment]
https://github.com/Billy2011/streamlink-27
is the python 2.7 fork.
Commits are merged and than adapt to python2.

**Comment by WanWizard** [comment]
Ok. So just to confirm, pin both develop and release on https://github.com/Billy2011/streamlink-27/commit/39f3855b59c2ef01f3d6513a1cc972968494a35c ?

**Comment by kueken** [comment]
In order to avoid mistakes, I would suggest this.
The supplementary 'files' are updated in parallel to the release.

**Pull request merged**
