### PR TITLE
Introduce enigma2-module to provide MACHINE name in /proc/stb/info/enigma2model

### PR DESCRIPTION
**Pull request by persianpros**
https://forums.openpli.org/topic/77494-one-proc-file-for-detecting-the-machine-in-all-enigma2-images/

### CODE REVIEW

**Comment by zgemma-star** [comment]
/proc/stb is driver part. We have already boxtype available as setting, this will in next driver been improved.

Please don't make a mess with this kind of code or just like osrelease and so on place it in /etc

**Comment by zgemma-star** [comment]
The driver name is in openpli machine name, so what do you gain with it?

**Comment by WanWizard** [comment]
There is a discussion about this on the forum. 

It's basically a workaround for missing boxbranding in OpenPLi, which should provide a unified interface layer to query the hardware, without having to deal with all the complexities and differences in runtime code.

**Comment by persianpros** [comment]
@zgemma-star 

There isn't any standard yet and a path isn't anything special.

**Comment by 68foxboris** [comment]
root@et1x000:~# cat /proc/stb/info/enigma2model
et1x000

root@et1x000:~# cat /proc/stb/info/model
dm800se

**Comment by zgemma-star** [comment]
First of all why use /proc/stb as this is generate by drivers. It's better to use a separate map like /proc/boxbranding
Second I see no advantage in this because machine/driver name is already provide in /proc/stb/info/model
I would advice to inform manufactures and fix it who use model name dm800se. It's easier in the end to make a small work-a-round for this "dm800se" boxes then make work-a-rounds in all images.

In the next driver release /proc/stb/info/boxtype will inform the type of box like H9 Twin, H9s and so on. I think only advance for this is that you can show other remote and frontpanel design under help button or owif.

**Comment by zgemma-star** [comment]
I am not against to add on some way identificiation but it must been clear if it's part of driver, images, enigma2, openembedded and so on.
Why not just use os-release and add machine info to it for the few boxes which send wrong info back...
https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/recipes-core/os-release/os-release.bb

**Comment by 68foxboris** [comment]
Unfortunately for ET 110004K nothing can be done. There is no support for a very long time.

**Comment by persianpros** [comment]
@68foxboris 

Most of times /proc/stb/info/model is fake.

**Pull request closed without merging**
