### PR TITLE
Update exteplayer3_git.bb

### PR DESCRIPTION
**Pull request by kueken**

### CODE REVIEW

**Comment by WanWizard** [comment]
This has broken all of last nights builds:
````
2019-04-30 11:00:08: Log data follows:
2019-04-30 11:00:08: | DEBUG: Executing shell function do_compile
2019-04-30 11:00:08: | /tmp/ccVkuDwd.o: In function `Write':
2019-04-30 11:00:08: | output_subtitle.c:(.text+0x954): undefined reference to `WriterSubPGS'
2019-04-30 11:00:08: | /tmp/ccs860al.o: In function `main':
2019-04-30 11:00:08: | exteplayer.c:(.text+0x2960): undefined reference to `PNGPlugin_init'
2019-04-30 11:00:08: | collect2: error: ld returned 1 exit status
2019-04-30 11:00:08: | WARNING: exit code 1 from a shell command.
````

**Comment by WanWizard** [comment]
Hmm... Might be because this PR wasn't merged before the build started...

**Comment by kueken** [comment]
Since there are missing exactly the two things that are after the change in exteplayer3.bb.
Would say again start the construction, there was the building still without change.

https://github.com/e2iplayer/exteplayer3/commit/0f7646823aee18e338ad75c1bd856eb2efad393b

**Comment by WanWizard** [comment]
Yes, I saw my mistake later, I've restarted the build run after I've updated.

**Pull request merged**
