### PR TITLE
Update openpli-common.conf

### PR DESCRIPTION
**Pull request by persianpros**
Add 'LOCALE_GENERATION_WITH_CROSS-LOCALEDEF_forcevariable = "0"' for recent linux distributions.

### CODE REVIEW

**Comment by persianpros** [comment]
See: https://github.com/PLi-metas/pli-extras/blob/develop/conf/layer.conf#L9

**Comment by eriksl** [comment]
What does it do.

**Comment by persianpros** [comment]
If you're going to build on a linux distro which features glibc 2.26 or newer (Ubuntu 18.04 LTS for example), then uncomment below line, more information: https://bugzilla.yoctoproject.org/show_bug.cgi?id=12265
# LOCALE_GENERATION_WITH_CROSS-LOCALEDEF_forcevariable = "0"

**Comment by betacentauri** [comment]
And why don’t you add the real fix mentioned in the bugzilla ticket?

**Comment by persianpros** [comment]
Ok I just did for our git: https://github.com/PLi-metas/pli-extras/commit/3e9cc8da86f62b986d4459851d66dd712281da3b

After test I'll let you know :)

**Comment by persianpros** [comment]
@betacentauri 
It didn't work, the patch applied but gives compile error so I did revert it.

**Pull request closed without merging**
