### PR TITLE
[mdev-mount.sh] add mount option noatime for all type filesystem

### PR DESCRIPTION
**Pull request by Dima73**
discussion here
http://forums.openpli.org/topic/41278-ssd-trim/?view=findpost&p=544398

### CODE REVIEW

**Comment by Taapat** [comment]
Maybe I am missing something, but why is it necessary variable FLAG?
Why not simply:
f ! mount -t auto -o noatime /dev/$MDEV "${MOUNTPOINT}" ; then

**Comment by Dima73** [comment]
This variable is an example for the future.
That's clearer.

**Comment by littlesat** [comment]
Can you please explain why this is required?
In addition I suggest we do not need that separete flag stuff.... when done it can simply be added as is.

**Comment by Dima73** [comment]
This option is consistent with the Milo

**Pull request merged**
