### PR TITLE
fix wifi for build

### PR DESCRIPTION
**Pull request by kueken**

### CODE REVIEW

**Comment by WanWizard** [comment]
You're deleting quite a lot here, does this still build for all supported kernel versions?

**Comment by kueken** [comment]
That looks like more than it is.
I can't build images for everyone.
I built kernel 4 and kernel 5.12 images for kernel 3.
et9x00
fusionhd
h7
osmio4k +
but it builds through completely.
Hopefully there are no other errors either.
Patches were adapted and recreated, since I assumed the current git in each case.

greetings

**Comment by kueken** [comment]
oh...i see one (PR ="2")
I'll take that out.
So you can react faster ;-)

**Comment by WanWizard** [comment]
In the meantime I'll setup a bitbake compile for these drivers, for all boxes. May take a while :grin:.

**Comment by kueken** [comment]
Of the deleted patches, 3 are no longer necessary due to updates in git.
2 I created together in one patch (new)
hope that it also builds for all receivers
I'm running out of memory on my laptop ;-)

**Comment by WanWizard** [comment]
We'll see what happens here. It may take a while, it starts compiling kernels first...

**Comment by WanWizard** [comment]
Was too quick, can't build them for all boxes, they don't build for kernels < 4.0.

Guess it's best to merge it, and see what happens tonight...

**Comment by kueken** [comment]
Kernel <4 
test with build et9x00 Kernel3.8 is ok

**Comment by WanWizard** [comment]
Does that mean we need to review the versions in https://github.com/OpenPLi/openpli-oe-core/blob/develop/meta-openpli/recipes-openpli/images/openpli-enigma2-feed.bb#L26 ?

**Comment by kueken** [comment]
Don't know exactly what you mean

The feed with the old kernel works without any problems, that's what I wanted to say.

**Comment by kueken** [comment]
gbue4k is currently building, but that takes a while with my ryzon5
build feed ok
h9 start......end
build feed ok

**Comment by kueken** [comment]
offtopic on
meta qt5 could be brought up to date 'zeus'.
For any 8.1

**Comment by WanWizard** [comment]
> Don't know exactly what you mean
````
	${@ 'kernel-module-8192fu' if ("${KERNEL_VERSION}" and bb.utils.vercmp_string("${KERNEL_VERSION}", '4.0') >= 0) else '' } \
	${@ 'kernel-module-8821cu' if ("${KERNEL_VERSION}" and bb.utils.vercmp_string("${KERNEL_VERSION}", '4.0') >= 0) else '' } \
	${@ 'kernel-module-88xxau' if ("${KERNEL_VERSION}" and bb.utils.vercmp_string("${KERNEL_VERSION}", '4.0') >= 0) else '' } \
````

These kernel modules are only build for kernels >= 4.0

**Comment by kueken** [comment]
mhh...
I'll see if I can fix something

kernel-module-8821cu is building with Kernel 3.8 (et9x00)
8192fu is classic problem (extern-inline and old Kernel)

**Comment by kueken** [comment]
8192fu fix for build Kernel <4

**Pull request merged**
