### PR TITLE
cdfs: support kernel 4.11

### PR DESCRIPTION
**Pull request by athoik**

### CODE REVIEW

**Comment by littlesat** [comment]
Please offer this merge request to develop (so we can cherry pick it to master)

**Comment by athoik** [comment]
There is no cdfs in develop!

**Comment by WanWizard** [comment]
@athoik does that mean develop doesn't support cdfs, or that it is implemented differently?

**Comment by athoik** [comment]
If i remember correctly we are now using gstreamer only!

**Comment by WanWizard** [comment]
Ok, thanks. :+1:

**Pull request merged**
