### PR TITLE
Keep dm8000 support and delete the rest, Check https://github.com/Ope…

### PR DESCRIPTION
**Pull request by persianpros**
…nPLi/enigma2/issues/920

### CODE REVIEW

**Comment by athoik** [comment]
There are people still build images for dm7020hd that has enough storage for develop... Also dm800se can work using flashexpander.

Better to use a BSP layer under OpenPLi and link as submodule.

**Comment by eriksl** [comment]
I do think this is a good idea, but it needs to be discussed within the team.

**Comment by ims21** [comment]
I agree with athoik

**Comment by persianpros** [comment]
@athoik @ims21 You can simply use "meta-local" ;)

**Comment by athoik** [comment]
meta-local for BSP layer?

I prefer meta-dream as submodule instead of deleting some models only.

**Comment by persianpros** [comment]
What I mean is you can what you want with what you have but why keep them on PLi ? ;)

**Comment by athoik** [comment]
ALL OR NOTHING :)

**Comment by persianpros** [comment]
+1 for nothing :D

**Comment by eriksl** [comment]
This was unintentionally closed by WanWizard by remove the relevant branch (which was necessary).

The members have decided that everyone that would like to build unsupported DMM models can always restore the missing models from the BSP. It's no use to us to keep unsupported models forever, and only adds complexity.

So this ís going to be applied, but only if it proves to be a sufficient quality patch.

**Comment by persianpros** [comment]
So what now ? I don't get it because I have to do everything again ...

**Comment by eriksl** [comment]
Applied in rc.

**Comment by ims21** [comment]
Thanks you, very much :-( !

**Pull request closed without merging**
