### PR TITLE
Enigma2: Add Multistream Support

### PR DESCRIPTION
**Pull request by athoik**
Add Multistream Support using an extra patch in order not to mess OpenPLi 4 users.

### CODE REVIEW

**Comment by littlesat** [comment]
Thanks.... But I do not think this is the way to do this..... Time to get a seperate brench for enigma2 for 5

**Comment by athoik** [comment]
Ok, let me know when branch is ready and used by OpenPLi next, in order make commits there.

**Comment by eriksl** [comment]
It's the next step now.

**Comment by athoik** [comment]
Ping

**Comment by littlesat** [comment]
This commit should be pushed to E2... as soon we have a stable branch for 4 and a saperate branch for 5...

**Pull request closed without merging**
