### PR TITLE
Backup Suite: license location update

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by athoik** [comment]
Why https://github.com/persianpros/BackupSuite is forked from https://github.com/openmb/BackupSuite instead of original source?

Strange...

**Comment by persianpros** [comment]
I did fork it from Pedro but when he deleted his repo github shows it like this, It's a github thing I guess ...
As you can see my fork is 129 commits ahead which can't be in less than a day and I have Pedro commits.

**Comment by athoik** [comment]
Better to create a new repo and push commits. Search will work also, now in forked repo it doesn't!

**Comment by persianpros** [comment]
Ok I'll do it next week.

**Pull request merged**
