### PR TITLE
try again make ffmpeg build better for size

### PR DESCRIPTION
**Pull request by kueken**
everything disabled. (muxer / demuxer / encoder ..)
required parameters activated separately.
Please check what is missing.

### CODE REVIEW

**Comment by fnordism** [comment]
Hi, yeah anything is disabled now, the whole binary is missing in the 8.0 release md5 367b5f5822b4530914e2a5fa2b9d84bb  ffmpeg_4.3.1-r0.0_mips32el.ipk
Absolutely useless package without a binary.

**Comment by WanWizard** [comment]
Check the develop build, to avoid us chasing ghosts...

**Comment by fnordism** [comment]
Hi WanWizard, i am building it now again using the develop branch.

**Comment by fnordism** [comment]
btw if you want to reduce the size of the binary, just use     --extra-cflags="${CFLAGS} -flto  ${HOST_CC_ARCH}${TOOLCHAIN_OPTIONS}" \
in ffmpeg_4.3.1.bb or in any other fat binary e.g busybox or python, lto is the way to go.

**Comment by WanWizard** [comment]
It was about more than just binary size, we needed to find 13MB before releasing 8.0, the full ffpmeg is very big if you have only 128MB flash space to play with... Having said that, obviously anything that helps achieving that goal is a plus... :grin:

**Comment by fnordism** [comment]
compress the binary(s) with UPX.


UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    281660 ->    113896   40.44%  linux/mipsel   ffmpeg           
upx compresses executables better than squashfs or ubifs or something
about 10-30%
I used upx even in systems with only 16mb ram, decompression needs a small amount of memory.

**Comment by WanWizard** [comment]
I'm up for any suggestions, as long as:
- it can be automated in a bitbake recipe
- it doesn't lead to functional image differences

For this reason I'm not to happy with stripping features for one set of boxes (MIPS in this case), as this discussion makes it clear what a support nightmare it has created.

Feel free to propose a solution.

**Pull request merged**
