### PR TITLE
enigma2-plugin-extensions-openwebif.bbappend: Add osninopro

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Review by athoik — COMMENTED** [review]
Did you forget osninopro.png?

**Comment by persianpros** [comment]
@athoik No I didn't forget about it but there is no such file here: https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/tree/master/plugin/public/images/boxes

**Comment by athoik** [comment]
So maybe you have to wait until osninopro.png committed on owif?

**Comment by persianpros** [comment]
So because of a box picture we should not have the correct remote?

**Comment by athoik** [comment]
Sure, use the correct box picture osninopro.png

**Pull request closed without merging**
