### PR TITLE
exteplayer3: update to version 35

### PR DESCRIPTION
**Pull request by athoik**

### CODE REVIEW

**Comment by littlesat** [comment]
We could consider to merge this... But shouldn't we do in develop instead?

**Comment by WanWizard** [comment]
Depends on whether this is a bugfix version (if so, what does it fix?) or a feature update.

**Comment by littlesat** [comment]
Is this a bugfix version?

**Comment by athoik** [comment]
It a feature, should go on develop.

https://github.com/samsamsam-iptvplayer/exteplayer3/commit/f55def46514c5a93f99bb203ad904dcde6d11e16

**Pull request closed without merging**
