### PR TITLE
meta-dream: remove unnecessary files.

### PR DESCRIPTION
**Pull request by Hains**
Nothing is using it.

### CODE REVIEW

**Comment by WanWizard** [comment]
Are you sure? I think there are quite a few DMM plugins that check the presence of tmpd?

**Comment by Hains** [comment]
Third-Party plugins perhaps? totally forgotten.

I will check 3th party plugins and close this PR in that case.

**Comment by WanWizard** [comment]
I don't know, except an old 7000 I've never owned a DMM box. But I vaguely recall this as the reason for leaving it in.

**Comment by Hains** [comment]
Yes i remember that too.
But it should belong to the past if i understand correctly(tpmd = tpm demon).
https://github.com/OpenPLi/openpli-oe-core/commit/061075a5acb0364ebe45cfc7baeeaf8ecb6da38b

But i will check third-party plugins this evening/tomorrow to be sure

**Comment by Hains** [comment]
tmpd is not installed on box. Even not built.
To be sure i  installed and excetuting the plugins:
-dreamexplorer
-dreamirc
- dream concinnity-hd-mod
-dreamexplorer

No problem
BTW: if i try to build tmpd, i get error:
ERROR: Nothing RPROVIDES 'libssl0.9.8x' (but /home/hains/github/openpli-oe-core/meta-dream/recipes-bsp/drivers/tpmd_1.0.bb RDEPENDS on or otherwise requires it)

So it seems harmless to me to remove these recipes.

**Pull request merged**
