### PR TITLE
remove, rename bitbake files which are provide by openembedded

### PR DESCRIPTION
**Pull request by wte-chromium**

### CODE REVIEW

**Comment by WanWizard** [comment]
Thanks, it's been a busy Sunday! :smile:

**Comment by WanWizard** [comment]
This version of ICU gives warnings about checksum errors, but builds, but after that the build of nodejs crashes with
````
error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory
`````

**Comment by wte-chromium** [comment]
libicui18n.so.58 was the old version, I think some packages has no depends on icu so it's not rebuild with the changes.

Now it's used version 64

**Comment by WanWizard** [comment]
Cleaned, rebuild the packages manually, rebuild nodejs-native, but nodejs now errors in the linker stage. Can't immediately find the issue....
````
collect2: error: ld returned 1 exit status
make[1]: *** [node.target.mk:167: /data/openpli/pli-oe/develop/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/nodejs/10.16.3-r0/node-v10.16.3/out/Release/node] Error 1
rm 3d4e2d7025a972fa3d517ebdc82f690a98aed56f.intermediate b064452ca01986ce2a02f85683a00e38c2576ba7.intermediate 6e74bf711fa810433e40be12e0f1c381c8b54609.intermediate
make: *** [Makefile:99: node] Error 2
WARNING: /data/openpli/pli-oe/develop/build/tmp/work/armv7ahf-neon-oe-linux-gnueabi/nodejs/10.16.3-r0/temp/run.do_compile.25235:1 exit 1 from 'exit 1'
````

**Comment by WanWizard** [comment]
Looks like it still looks for v58 for some reason:
````
undefined reference to `icu_58::ByteSink::~ByteSink()'
````

**Comment by wte-chromium** [comment]
Strange I build for 5 boxes, mipsel and arm and didn't get this issue on nodejs or other packages.
Webkit and chromium mostly uses the icu. I saw in Gigablue that it had some closed source stuff which maybe is uses specific icu packages.

Which box did you have this issue with. Then I will check what causes it and see if icu 58 is really needed.

**Comment by WanWizard** [comment]
In the end, I needed to cleanall both icu and nodejs-native, they have now build overnight.

The only thing left seems to be an issue in OE:
````
WARNING: icu-64.2-r0 do_fetch: Checksum mismatch for local file /data/openpli/sources/icu4c-64_2-src.tgz
Cleaning and trying again.
WARNING: icu-64.2-r0 do_fetch: Renaming /data/openpli/sources/icu4c-64_2-src.tgz to /data/openpli/sources/icu4c-64_2-src.tgz_bad-checksum_b590012e21bb5d23342c111081b120c3
WARNING: icu-64.2-r0 do_fetch: Checksum failure encountered with download of http://download.icu-project.org/files/icu4c/64.2/icu4c-64_2-src.tgz - will attempt other sources if available
````

**Pull request merged**
