### PR TITLE
PlexDVRAPI: update .bb

### PR DESCRIPTION
**Pull request by Huevos**
Updated to read version from PLUGIN_VERSION created during build. 

Related commit: https://github.com/OpenViX/PlexDVRAPI/commit/e146d3ce1adfd18e39e3ebb7817c6d0bb7fbf668

### CODE REVIEW

**Comment by athoik** [comment]
The SRCREV is not required. 

Mentioned before: https://github.com/OpenPLi/openpli-oe-core/pull/331#pullrequestreview-65266205 , https://github.com/OpenPLi/openpli-oe-core/commit/ae4c1c2a39222d8ba4b7eb91a8d3411aa9a736cc

Regarding the do_install_prepend it's better to use also `${S}`, having the full path to install file is better, especially in out of tree compiles.

Here is how patch should look after applying above changes.

```
--- a/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-systemplugins-plexdvrapi.bb
+++ b/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-systemplugins-plexdvrapi.bb
@@ -6,7 +6,7 @@ LIC_FILES_CHKSUM = "file://LICENSE;md5=a23a74b3f4caf9616230789d94217acb"

 inherit gitpkgv distutils-openplugins
 PV = "3.0+git${SRCPV}"
-PKGV = "3.0+git${GITPKGV}"
+PKGV = "${GITPKGVTAG}"

 SRC_URI = "git://github.com/OpenViX/PlexDVRAPI.git;protocol=git"

@@ -16,6 +16,10 @@ RDEPENDS_${PN} = " \
     python-argparse \
     "

+do_install_prepend() {
+       echo ${GITPKGVTAG} | awk -F"-" '{print $1}'> ${S}/build/lib/SystemPlugins/PlexDVRAPI/PLUGIN_VERSION
+}
+
 python populate_packages_prepend() {
     e2_pdir = bb.data.expand('${libdir}/enigma2/python/Plugins', d)
     do_split_packages(d, e2_pdir, '^(\w+/\w+)/.*\.py$', 'enigma2-plugin-%s-src', '%s (source files)', recursive=True, match_path=True, prepend=True)
```

**Comment by andyblac** [comment]
I'll get the PR redone, only one thing the PV does not require the version number when using PKGV = "${GITPKGVTAG}", PV = "git${SRCPV}" is good enough.

**Comment by andyblac** [comment]
it seems SRCREV is required
 
```Loaded 3971 entries from dependency cache.
ERROR: ExpansionError during parsing /home/vixdev/5.0/meta-oe-alliance/meta-oe/recipes-mediacenter/plex/enigma2-plugin-systemplugins-plexdvrapi.bb###########################################################              | ETA:  0:00:00
Traceback (most recent call last):
  File "/home/vixdev/5.0/bitbake/lib/bb/data_smart.py", line 412, in DataSmart.expandWithRefs(s='git${SRCPV}', varname='PV'):
                 try:
    >                s = __expand_var_regexp__.sub(varparse.var_sub, s)
                     try:
  File "/home/vixdev/5.0/bitbake/lib/bb/data_smart.py", line 111, in VariableParse.var_sub(match=<_sre.SRE_Match object; span=(3, 11), match='${SRCPV}'>):
                 else:
    >                var = self.d.getVarFlag(key, "_content")
                 self.references.add(key)
  File "/home/vixdev/5.0/bitbake/lib/bb/data_smart.py", line 773, in DataSmart.getVarFlag(var='SRCPV', flag='_content', expand=True, noweakdefault=False, parsing=False):
                     cachename = var + "[" + flag + "]"
    >            value = self.expand(value, cachename)
     
  File "/home/vixdev/5.0/bitbake/lib/bb/data_smart.py", line 436, in DataSmart.expand(s='${@bb.fetch2.get_srcrev(d)}', varname='SRCPV'):
         def expand(self, s, varname = None):
    >        return self.expandWithRefs(s, varname).value
     
  File "/home/vixdev/5.0/bitbake/lib/bb/data_smart.py", line 426, in DataSmart.expandWithRefs(s='${@bb.fetch2.get_srcrev(d)}', varname='SRCPV'):
                 except Exception as exc:
    >                raise ExpansionError(varname, s, exc) from exc
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure for URL: 'git://github.com/OpenViX/PlexDVRAPI.git;protocol=git'. Please set a valid SRCREV for url ['SRCREV_default_pn-enigma2-plugin-systemplugins-plexdvrapi', 'SRCREV_default', 'SRCREV_pn-enigma2-plugin-systemplugins-plexdvrapi', 'SRCREV'] (possible key names are git://github.com/OpenViX/PlexDVRAPI.git;protocol=git, or use a ;rev=X URL parameter)
```

**Comment by andyblac** [comment]
ahh I remember now you call it in here https://github.com/Huevos/openpli-oe-core/blob/ee98c86d33a7f02c718a8935d0dca8484d5667c5/meta-openpli/conf/distro/reporefs.conf#L25 I'll get it removed from the PR.

**Pull request closed without merging**
