### PR TITLE
Update url e2iplayer dependencies

### PR DESCRIPTION
**Pull request by Hains**
samsamsam-iptvplayer => e2iplayer.

Repo samsamsam-iptvplayer is deleted.

### CODE REVIEW

**Comment by WanWizard** [comment]
We've noticed, very handy. Not. :-1: 

Thanks!

**Comment by Hains** [comment]
But no lsdir. 
We have (temporarily?) 
https://github.com/OpenVisionE2/lsdir

Is that acceptable?

**Comment by WanWizard** [comment]
Just fixed.

It is only a single c source file, which is old (not from samsamsam anyway), and will never change, so we've opted for a tarball instead of a repo dependency.

**Comment by WanWizard** [comment]
Appearently two more are about to go (but fortunately not gone yet):
> gstplayer: gone to https://gitlab.com/e2i/gstplayer
>gst-ifdsrc: gone to https://gitlab.com/e2i/gst-ifdsrc

would you be able to have a look at those? This seems to be more than simply changing repo's, with my very limited knowledge, I can't get them to compile...

**Pull request merged**
