### PR TITLE
Update enigma2-plugin-extensions-epgimport-rytec.bb

### PR DESCRIPTION
**Pull request by doglover3920**
SLO integrated

### CODE REVIEW

**Comment by persianpros** [comment]
https://github.com/OpenPLi/openpli-oe-core/pull/486
https://github.com/OpenPLi/openpli-oe-core/pull/487

**Comment by WanWizard** [comment]
Three identical PR's?

**Comment by doglover3920** [comment]
I never know in which version I have to change things.
So I added in version 6, 6.1 and 6.2

**Comment by WanWizard** [comment]
The only images being build are
- the last minor release of the current major version (now 6.2)
- the last minor release of the previous major version (now 4)
So no need to update branches 6.0 and 6.1, they are not build anymore. But 4 still needs the update. I'll do that for you.

**Comment by WanWizard** [comment]
openpli-4 updated here: https://github.com/OpenPLi/openpli-oe-core/commit/66d098f64556d6e1f7dca453dcf8e1130102d580

**Pull request merged**
