### PR TITLE
Introduce dima-plugins folder:

### PR DESCRIPTION
**Pull request by persianpros**
- Move all https://github.com/Dima73 plugins to its specific folder and manage them via inc file.
- Add 3 missing plugins: enigma2-plugin-extensions-sundtekcontrolcenter, enigma2-plugin-extensions-ts-sateditor and enigma2-plugin-systemplugins-devicemanager
- Add missing plugins to the feeds so remove them from 3rdparty feeds as you could compile them from the sources now.
- reporefs now has dima-plugins section for easy management.

### CODE REVIEW

**Comment by persianpros** [comment]
@WanWizard I can't check this as I don't have a compile system to test but seems ok to me as I'm good with recipes but you could check it I guess.

**Comment by WanWizard** [comment]
First build test:
````
ERROR: Nothing RPROVIDES 'exfat-fuse' (but /data/openpli/oe/develop/meta-openpli/recipes-openpli/dima-plugins/enigma2-plugin-systemplugins-devicemanager.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'exfat-fuse' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['exfat-fuse']
ERROR: Required build target 'openpli-enigma2-feed' has no buildable providers.
Missing or unbuildable dependency chain was: ['openpli-enigma2-feed', 'enigma2-plugin-systemplugins-devicemanager', 'exfat-fuse']
````

**Comment by persianpros** [comment]
It's because what @Dima73 recommended in https://github.com/OpenPLi/openpli-oe-core/blob/ddf2348f3d1d40ee251cb4c812868acedf026ff1/meta-openpli/recipes-openpli/dima-plugins/enigma2-plugin-systemplugins-devicemanager.bb#L9 which you can comment for now to test the build.

**Comment by blzr** [comment]
it should be fuse-exfat

**Comment by blzr** [comment]
other than above, devicemanager, sundtekcontrolcenter and ts-sateditor all fails at "do_populate_lic: Fatal QA errors found, failing task" 
- lic_file_chksum point to README while they have README.md (which say nothing on actual license anyway ;-))

**Comment by blzr** [comment]
in addition devicemanger:
File "setup.py", line 5
    setup(name = 'enigma2-plugin-systemplugins-devicemanager
                                                                  ^
SyntaxError: EOL while scanning string literal

**Comment by persianpros** [comment]
Thank you @blzr I just applied the fixes and @Dima73 just fixed devicemanager: https://github.com/Dima73/enigma2-plugin-systemplugins-devicemanager/commit/7f99e926eb4d5da0df484dfbee1f097a81cb45b6

As I don't have a compile system I can't compile so thanks a lot for testing, I hope now everything works.

**Comment by WanWizard** [comment]
This compiles.

**Comment by persianpros** [comment]
So check ipks in your 3rdparty feeds and remove if any of these 3 added plugins are there.

**Comment by WanWizard** [comment]
Can't do that now, as develop shares the feed with 7.3-release. I first have to create an OpenPLi-8 feed for third party.

**Comment by WanWizard** [comment]
I've created an openpli-8-release feed for 3rd-party packages, and removed the duplicates.

**Comment by persianpros** [comment]
Hmm but http://downloads.openpli.org/feeds/openpli-8-release/3rd-party/Packages.gz won't work for me to check.

**Comment by WanWizard** [comment]
May take a while before the mirrors are populated...

**Comment by persianpros** [comment]
@WanWizard 

I think you missed enigma2-plugin-extensions-sundtekcontrolcenter as it's on the new 3rdoartu feed still.

**Comment by WanWizard** [comment]
The feed isn't automatically updated, we can't do that (due to the way it is automated) until we have an 8.0-rc build.

**Pull request merged**
