### PR TITLE
created new version of python-wifi, python3 compatible, and python2 is still working

### PR DESCRIPTION
**Pull request by Opvolger**
This is my 1ste pull request. I have made python-wifi compatible for python2/3 and 32/64 cpu's

So no path is needed and it will work if enigma2 will go to python3

TESTED on Zgemma H9S with a WiFi dongle.

### CODE REVIEW

**Comment by athoik** [comment]
Out of curiosity the python-wifi maintainer did not accepted the patches for python3? 

https://pypi.org/project/python-wifi/

**Comment by Opvolger** [comment]
No I haven't done that (yet). Can try, but since it was still 32 bit and the patch to 64 bit never reached it either. So I think it is a lost cause. The repo has not been touched for over 6 years

**Comment by WanWizard** [comment]
You could try via email: robinson@tuxfamily.org (the last known maintainer)

**Comment by WanWizard** [comment]
Any update on this?

**Comment by Opvolger** [comment]
Due to illness in the family and unfortunately ultimately a death, I did not get around to this at all. Will pick it up (send the mail)

**Comment by athoik** [comment]
I am really sorry for your loss.

Please merge the patch, we can switch to updated wifi module at any time.

**Comment by WanWizard** [comment]
So sorry to hear that, my condolances.

**Pull request merged**
