### PR TITLE
qtwebengine add alsa for all models

### PR DESCRIPTION
**Pull request by zgemma-star**
All models support alsa, this improves glitching of audio/video

### CODE REVIEW

**Comment by WanWizard** [comment]
With this PR (or related qt5 PR's) merged, nothing builds anymore:
````
ERROR: Nothing PROVIDES 'virtual/egl' (but /openpli/oe/develop/meta-qt5/recipes-qt/qt5/qtbase_git.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'qtwebkit' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qtwebkit', 'qtbase', 'virtual/egl']
ERROR: Required build target 'openpli-enigma2-feed' has no buildable providers.
Missing or unbuildable dependency chain was: ['openpli-enigma2-feed', 'enigma2-plugin-extensions-qtstalker', 'qtwebkit', 'qtbase', 'virtual/egl']
````

**Comment by kueken** [comment]
no problem here
wich box?

**Comment by WanWizard** [comment]
This was an SFX6008, but in the forum others complain too.

**Comment by kueken** [comment]
Will check the sf6008, but so far no errors can be seen here.
The changes also had no effect on the error appearing above.

**Comment by kueken** [comment]
So I can find the conflict of the sfx6008.
support?
Does the box exist?
I would first disable feature qt plugins there.
I can't see any other problems.
Sfx6008 problem was there before.

**Comment by kueken** [comment]
There are more errors in the construction of the sfx6008, either temporarily disable them completely, or currently accept them?

**Comment by WanWizard** [comment]
Leave the sfx6008 for the moment, as said @ims21 also complained about build failures...

**Comment by kueken** [comment]
During the night I tested the 4 standard test boxes.
All flawless.
I have already communicated my assumption of the possible problems and the solution.
Please test again.
From my point of view disable the sfx6008.
The sfx6008 is the odd box with very poor support and questionable existence.

**Comment by WanWizard** [comment]
We'll see, once I've fixed the SFX6008 BSP I'll start another full build run.

**Comment by kueken** [comment]
https://github.com/OpenPLi/openpli-oe-core/commit/8000924cd71166fb311468d16d3898a96879ae98
https://github.com/OpenPLi/openpli-oe-core/commit/2349f2efc5c849e7064f728fb40a11afb5c3a092

Feedback at pli-Forum?

**Comment by WanWizard** [comment]
SFX6008 now builds, I have started a full build run. Lets see what happens...

**Pull request merged**
