### PR TITLE
Add libvpx 1.6.1 as the old version won't compile in Ubuntu 18.04 LTS

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by eriksl** [comment]
Shouldn't it replace the old version then?

**Comment by persianpros** [comment]
I don't know, we use it like this in pli-extras: https://github.com/PLi-metas/pli-extras/tree/develop/recipes-multimedia/webm

**Comment by eriksl** [comment]
That's not OpenPLi's concern ;-)

**Comment by persianpros** [comment]
Yeah but without this we can't compile on Ubuntu 18.04 LTS.

**Comment by eriksl** [comment]
AFAIK OpenPLi doesn't use vpx at all?

If that's the case, I suggest replacing it instead of adding it.

**Pull request closed without merging**
