### PR TITLE
Samba improvements

### PR DESCRIPTION
**Pull request by Taapat**
See explanations in commits.

### CODE REVIEW

**Comment by WanWizard** [comment]
can you revert "samba: add smb.conf in conffiles" from this PR, and send it in on a new PR onto the R/C branch? I think we should fix that for 6.0.

**Comment by Taapat** [comment]
Done!
But I'm afraid that because of the crazy cross dependencies between samba, libsamba and libsamba-base, samba you can not normally update from feed on rc.

**Comment by Taapat** [comment]
This PR should fix these cross dependencies.

**Comment by eriksl** [comment]
All applied to develop.

**Pull request merged**
