### PR TITLE
Introduce OpenHAL support, more information: https://forums.openpli.o…

### PR DESCRIPTION
**Pull request by persianpros**
…rg/topic/77494-one-proc-file-for-detecting-the-machine-in-all-enigma2-images/

### CODE REVIEW

**Comment by persianpros** [comment]
Ok https://github.com/OpenEnigma2 is up!

This is the start so please merge the PR and start building develop images with it and test the results, more PRs are comming for your metas to support some variables you don't have.

Also some PRs for enigma2 develop branch so develop images would be with the new module and we could start change the future :+1:

**Comment by WanWizard** [comment]
@openpli do not merge until after 8.0 release !

**Comment by persianpros** [comment]
It's ok, I'm sending the PRs for develop branch so merge whenever you want.

This should not be in release.

**Comment by WanWizard** [comment]
We need to keep develop stable at the moment, to make bugfixing on 8.0-rc easier.

**Comment by 68foxboris** [comment]
I added for verification.
`
model=et1x000
brand=xtrend
platform=et1x000
feedsurl=http://ednaz.tvfaq.net/foxbob-feed
distro=openpli
oe=
kernel=4.1.37
python=
mediaservice=enigma2-plugin-systemplugins-servicemp3
multilib=False
architecture=cortexa15hf-neon-vfpv4
socfamily=bcm7251s
blindscanbinary=avl_xtrend_blindscan
rctype=504
rcname=et7x00mini
rcidnum=2
imagedir=et1x000
imagefs=tar.bz2 
mtdbootfs=
mtdrootfs=mmcblk0p4
mtdkernel=mmcblk0p3
rootfile=rootfs.tar.bz2
kernelfile=kernel.bin
mkubifs=
ubinize=
compiledate=20201221
fpu=hard
displaytype=textlcd 7segment            
transcoding=False
multitranscoding=False
hdmi=True
yuv=False
rca=False
avjack=False
scart=False
dvi=False
svideo=False
hdmihdin=False
hdmifhdin=False
wol=False
ci=True
fhdskin=True
`

**Pull request closed without merging**
