### PR TITLE
init-ifupdown_1.0.bbappend: Fix parse error

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by ims21** [comment]
SRC_URI +=

**Comment by persianpros** [comment]
Yeah I have a reason for "append" and "+", you can check it yourself as I did and it's ok ;)

**Comment by eriksl** [comment]
You're not supposed to use += on an _append.

**Comment by WanWizard** [comment]
Never commit things late at night..., should indeed be +=.

**Pull request closed without merging**
