### PR TITLE
Zeus kodi18

### PR DESCRIPTION
**Pull request by HD-Digital**

### CODE REVIEW

**Comment by athoik** [comment]
Thanks!

**Comment by HD-Digital** [comment]
Remove ffmpeg 3.4.2 bbappend as kodi relay on the openembedded version 4.2.1
https://github.com/OpenPLi/openpli-oe-core/tree/zeus/meta-openpli/recipes-multimedia/ffmpeg

**Comment by athoik** [comment]
Only bbappend should be removed or the whole ffmpeg directory?

**Comment by HD-Digital** [comment]
https://github.com/OpenPLi/openpli-oe-core/pull/790

Maybe this is for now best middle way. I do not know if someone still needs 3.4.2

**Pull request merged**
